# Generated by Django 5.0.2 on 2024-02-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
    ]
